Maybe
cbowdon/TsMonad pull request #39
Opened 2017-07-01 08:12 UTC by piq9117

Issue https://github.com/cbowdon/TsMonad/issues/31. added nullable type and return type on Maybe.maybe.

2017-07-01 08:12 UTC, piq9117 commented
npm5 may have added a `package-lock.json` 😅

2017-07-03 07:37 UTC, ahstro commented
I would assume, that since this project has a `yarn.lock` file, you should be using `yarn` with it and remove the `package-lock.json` file 🙂

2017-07-04 07:12 UTC, ahstro requested changes
(Sorry for hijacking your project @cbowdon, let me know if I shouldn't 😅 )

2017-07-04 07:12 UTC, ahstro commented on src/maybe.ts
> +    static maybe<T>(t?: T): Maybe<T> {
You'll probably want to change `T` to `T | null` since `strictNullChecks` removes `null` from the domain of every type.

2017-07-04 07:20 UTC, piq9117 commented on src/maybe.ts
> +    static maybe<T>(t?: T): Maybe<T> {
Thank you for your patience and guidance! I will be making this change. 😃

2017-07-04 07:54 UTC, ahstro commented
You might also want to squash your commits into one by using `git rebase --interactive` since a lot of them simply undo themselves and it makes for a cleaner commit history 🙂

2017-07-04 08:41 UTC, ahstro commented
Looks like you're having some trouble? 😉 To rebase, use `git rebase --interactive {earliset_commit_hash}^`, so this would be `git rebase --interactive a47aa0a055eaf47d709997b11669a92ed08c6afe^`. You'll then be presented with something like this in your editor of choice:

```
pick 5e4253f18 commit message 1
pick c314c5c39 commit message 2
pick 5a80c24f8 commit message 3
```

change the first `pick` to `reword` and the rest to `fixup`, like this.

```
reword 5e4253f18 commit message 1
fixup c314c5c39 commit message 2
fixup 5a80c24f8 commit message 3
```

Save and exit. You'll then get a file saying `commit message 1`, change this to your preferred commit message. Save and exit again. Now `git push --force` that to this branch.

I hope that made some sense. 😅

2017-07-04 08:57 UTC, piq9117 commented
😅 yes! I was having trouble doing that. Your instructions made more sense that the tutorial I was watching.

2017-07-21 11:26 UTC, cbowdon commented
@ahstro I'm very grateful for you 'hijacking' the project, thank you for helping! 😄 

@piq9117 Thanks for this PR!  Looks good to me.

2017-07-21 11:27 UTC, merged